language: node_js
node_js: "10.15.0"
os:
  - linux
  - osx
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
  - 'npm install -g vsce'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
  - 'vsce package'
script:
  - 'npm test --silent'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && "${TRAVIS_OS_NAME}" = "linux" ]]; then
    sonar-scanner;
    fi
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
addons:
  sonarcloud:
    organization: "jboss-fuse"
    branches:
      - master
    
